name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Start SQL Server
        run: |
           docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Sleep 5s
        uses: jakejarvis/wait-action@master
        with:
            time: '5s'
      
      - name: Cache Primes
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ./out

 #     - name: Deploy to Azure
  #      uses: azure/webapps-deploy@v2
   #     with:
    #      app-name: demo-ci-cd-api
     #     publish-profile: ${{ secrets.AZURE_WEBAPP }}
      #    package: ./out
